# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Cucumber Test Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew -Dspring.profiles.active="QA" -Dtype="ui" clean test
    - name: Generate Code Coverage report
      run: ./gradlew jacocoTestReport
    - name: Publish Code Coverage report
      run: bash <(curl -s https://codecov.io/bash) -t 5bf8edb1-d187-4e66-95eb-1fcdeebce5a5
    - name: Publishing extent report
      uses: actions/upload-artifact@v2
      with:
        name: Extent Test Report
        path: ${{ github.workspace }}/test-output/html-report/test-report.html